spring:
  config:
    activate:
      on-profile: local
---
spring:
  profiles: dev
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
        - localhost:9093
        - localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap.servers:
          - localhost:9092
          - localhost:9093
          - localhost:9094
---
spring:
  profiles: staging
  kafka:
    producer:
      bootstrap-servers:
        - staging:9092
        - staging:9093
        - staging:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
---
---
spring:
  profiles: prod
  kafka:
    producer:
      bootstrap-servers:
        - prod:9092
        - prod:9093
        - prod:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer